'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '@/lib/supabase'
import {
  adminUpdateMemoryPin,
  adminUpdateMemoryStory,
  moveMemoryPin,
  moveMemoryStory,
} from '@/lib/memory-map/mutations'
import { isAutoGeneratedMemoryTitle } from '@/lib/memory-map/validation'
import {
  governanceFlagsFromChecks,
  parseTagsInput,
  type AdminStoryReviewDraft,
} from '@/lib/memory-map/admin-story-review'
import {
  formatStoryReviewLocationSummary,
  getStoryReviewMapInitialView,
} from '@/lib/memory-map/map-starting-point'
import type { MapPlacement, MemoryArea, MemoryCategory, MemoryMap, MemoryPin, MemoryStory, RiskLevel } from '@/lib/memory-map/types'
import { pinStats, storyTypeLabel } from '@/lib/memory-map/utils'
import MapCanvas from '@/components/memory-map/MapCanvas'
import StatusBadge, { RiskBadge } from '@/components/memory-map/StatusBadge'
import StoryGovernancePanel, {
  defaultGovernanceChecks,
  type GovernanceChecks,
} from '@/components/memory-map/admin/StoryGovernancePanel'
import StoryApprovalSummary, { needsPublishConfirmation } from '@/components/memory-map/admin/StoryApprovalSummary'
import {
  cannotApproveOwnStory,
  isOwnStoryPlatformOverride,
  OWN_STORY_APPROVAL_MESSAGE,
  PLATFORM_ADMIN_OVERRIDE_NOTE,
} from '@/lib/memory-map/own-story-approval'

type Props = {
  story: MemoryStory
  pin: MemoryPin | null
  area: MemoryArea | null
  categories: MemoryCategory[]
  areas: MemoryArea[]
  pins: MemoryPin[]
  stories: MemoryStory[]
  map: MemoryMap
  busy: boolean
  currentUserId: string | null
  isAppAdmin: boolean
  onClose: () => void
  onRefresh: () => Promise<void>
  onApprove: (approvalNote?: string) => Promise<boolean>
  onReject: () => void
}

function draftFromStory(story: MemoryStory, pin: MemoryPin | null): AdminStoryReviewDraft {
  return {
    title: story.title,
    description: story.description ?? '',
    eventYear: String(story.event_year),
    eventDate: story.event_date ?? '',
    loggedByDisplayName: story.logged_by_display_name ?? '',
    riskLevel: story.risk_level,
    tagsInput: (story.tags ?? []).join(', '),
    pinTitle: pin?.title ?? '',
    pinDescription: pin?.description ?? '',
    pinCategoryId: pin?.category_id ?? '',
  }
}

export default function AdminStoryReviewPanel({
  story,
  pin,
  area,
  categories,
  areas,
  pins,
  stories,
  map,
  busy,
  currentUserId,
  isAppAdmin,
  onClose,
  onRefresh,
  onApprove,
  onReject,
}: Props) {
  const [draft, setDraft] = useState(() => draftFromStory(story, pin))
  const [governanceChecks, setGovernanceChecks] = useState<GovernanceChecks>(() => defaultGovernanceChecks(story))
  const [approvalNote, setApprovalNote] = useState('')
  const [publishConfirmed, setPublishConfirmed] = useState(false)
  const [movePinMode, setMovePinMode] = useState(false)
  const [placement, setPlacement] = useState<MapPlacement | null>(
    pin ? { lat: pin.lat, lng: pin.lng, x: pin.x_position, y: pin.y_position } : null
  )
  const [moveStoryOpen, setMoveStoryOpen] = useState(false)
  const [moveAreaId, setMoveAreaId] = useState(pin?.area_id ?? areas[0]?.id ?? '')
  const [movePinId, setMovePinId] = useState<string | null>(null)
  const [moveNewPinTitle, setMoveNewPinTitle] = useState('')
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    setDraft(draftFromStory(story, pin))
    setGovernanceChecks(defaultGovernanceChecks(story))
    setPlacement(pin ? { lat: pin.lat, lng: pin.lng, x: pin.x_position, y: pin.y_position } : null)
    setMovePinMode(false)
    setMoveStoryOpen(false)
    setError('')
  }, [story, pin])

  const mapMode = area?.map_type === 'image' ? 'image' : 'geo'
  const pinStoryCount = pin
    ? stories.filter((s) => s.pin_id === pin.id && !['deleted', 'archived'].includes(s.status)).length
    : 0

  const displayPin = useMemo(() => {
    if (!pin) return null
    if (!placement) return pin
    return {
      ...pin,
      lat: placement.lat ?? pin.lat,
      lng: placement.lng ?? pin.lng,
      x_position: placement.x ?? pin.x_position,
      y_position: placement.y ?? pin.y_position,
    }
  }, [pin, placement])

  const mapView = useMemo(() => {
    if (!area || !displayPin) return null
    return getStoryReviewMapInitialView({
      pin: displayPin,
      area,
      memoryMap: map,
      pins,
      placement,
    })
  }, [area, displayPin, map, pins, placement])

  const locateTarget = useMemo(() => {
    if (mapMode !== 'geo' || !displayPin?.lat || displayPin.lng == null) return null
    return { lat: displayPin.lat, lng: displayPin.lng }
  }, [mapMode, displayPin?.lat, displayPin?.lng])

  const locationSummary = area && displayPin ? formatStoryReviewLocationSummary(area, displayPin, placement) : null
  const mapPins = displayPin ? [displayPin] : []

  const autoTitle = isAutoGeneratedMemoryTitle(draft.title, draft.pinTitle, draft.eventYear)
  const needsConfirm = needsPublishConfirmation({ ...story, risk_level: draft.riskLevel }, governanceChecks)
  const ownStoryBlocked = cannotApproveOwnStory(story, currentUserId, isAppAdmin)
  const platformOverride = isOwnStoryPlatformOverride(story, currentUserId, isAppAdmin)

  async function saveChanges(): Promise<boolean> {
    if (!pin) return true
    setSaving(true)
    setError('')
    const year = parseInt(draft.eventYear, 10)
    if (Number.isNaN(year)) {
      setError('Valid year required.')
      setSaving(false)
      return false
    }

    const { error: storyErr } = await adminUpdateMemoryStory(supabase, {
      storyId: story.id,
      title: draft.title.trim(),
      description: draft.description,
      eventYear: year,
      eventDate: draft.eventDate || null,
      loggedByDisplayName: draft.loggedByDisplayName || null,
      riskLevel: draft.riskLevel,
      governanceFlags: governanceFlagsFromChecks(governanceChecks),
      tags: parseTagsInput(draft.tagsInput),
    })
    if (storyErr) {
      setError(storyErr)
      setSaving(false)
      return false
    }

    const { error: pinErr } = await adminUpdateMemoryPin(supabase, {
      pinId: pin.id,
      title: draft.pinTitle.trim(),
      description: draft.pinDescription || null,
      categoryId: draft.pinCategoryId || null,
    })
    if (pinErr) {
      setError(pinErr)
      setSaving(false)
      return false
    }

    if (
      placement &&
      (placement.lat !== pin.lat ||
        placement.lng !== pin.lng ||
        placement.x !== pin.x_position ||
        placement.y !== pin.y_position)
    ) {
      const { error: moveErr } = await moveMemoryPin(supabase, pin.id, placement)
      if (moveErr) {
        setError(moveErr)
        setSaving(false)
        return false
      }
    }

    setSaving(false)
    await onRefresh()
    return true
  }

  async function onSave() {
    const ok = await saveChanges()
    if (ok) setMovePinMode(false)
  }

  async function onApproveClick() {
    if (ownStoryBlocked) {
      setError(OWN_STORY_APPROVAL_MESSAGE)
      return
    }
    if (needsConfirm && !publishConfirmed) {
      setError('Confirm you have reviewed this story before publishing.')
      return
    }
    const saved = await saveChanges()
    if (!saved) return
    await onApprove(approvalNote.trim() || undefined)
  }

  async function onMoveStorySubmit() {
    setSaving(true)
    setError('')
    if (movePinId) {
      const { error: err } = await moveMemoryStory(supabase, story.id, movePinId, null)
      setSaving(false)
      if (err) {
        setError(err)
        return
      }
    } else if (moveNewPinTitle.trim()) {
      const { error: err } = await moveMemoryStory(supabase, story.id, null, {
        area_id: moveAreaId,
        category_id: draft.pinCategoryId || categories[0]?.id || '',
        title: moveNewPinTitle.trim(),
        status: 'pending',
        lat: placement?.lat ?? null,
        lng: placement?.lng ?? null,
        x: placement?.x ?? null,
        y: placement?.y ?? null,
      })
      setSaving(false)
      if (err) {
        setError(err)
        return
      }
    } else {
      setSaving(false)
      setError('Select a pin or enter a new pin name.')
      return
    }
    setMoveStoryOpen(false)
    await onRefresh()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-2 sm:items-center sm:p-4">
      <div className="mm-card flex max-h-[92dvh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl">
        <div className="shrink-0 border-b border-white/10 px-4 py-3">
          <div className="flex items-start justify-between gap-3">
            <div className="min-w-0">
              <h3 className="truncate text-lg font-black">{draft.title}</h3>
              <p className="mm-muted mt-1 text-xs">
                {area?.name ?? '—'} · {draft.pinTitle || '—'} · {draft.loggedByDisplayName || 'Contributor'}
              </p>
              <div className="mt-2 flex flex-wrap gap-2">
                <StatusBadge status={story.status} />
                <RiskBadge level={draft.riskLevel} />
                <span className="rounded-full bg-white/10 px-2 py-0.5 text-[10px] font-bold uppercase">
                  {storyTypeLabel(story.story_type)}
                </span>
              </div>
            </div>
            <button type="button" onClick={onClose} className="text-xl text-white/50" aria-label="Close">
              ×
            </button>
          </div>
          {autoTitle ? (
            <p className="mt-2 text-xs text-amber-200">Auto-generated title. You can edit before approving.</p>
          ) : null}
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto px-4 py-4">
          {error ? (
            <p className="mb-3 rounded-xl border border-red-400/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">{error}</p>
          ) : null}

          {story.media && story.media.length > 0 ? (
            <section className="mb-4">
              <p className="mb-2 text-xs font-bold uppercase tracking-wide text-white/50">Media</p>
              <div className="grid gap-2 sm:grid-cols-2">
                {story.media.map((m) =>
                  m.media_type === 'image' ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img key={m.id} src={m.file_url} alt="" className="max-h-64 w-full rounded-xl object-cover" />
                  ) : (
                    <video key={m.id} src={m.file_url} controls className="max-h-64 w-full rounded-xl" />
                  )
                )}
              </div>
            </section>
          ) : story.description ? (
            <section className="mb-4 mm-card rounded-xl p-3 text-sm whitespace-pre-wrap">{story.description}</section>
          ) : null}

          {area && pin ? (
            <section className="mb-4">
              <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
                <p className="text-xs font-bold uppercase tracking-wide text-white/50">Map location</p>
                <button
                  type="button"
                  onClick={() => setMovePinMode((v) => !v)}
                  className="mm-btn-secondary rounded-lg px-3 py-1 text-xs font-bold"
                >
                  {movePinMode ? 'Done moving' : 'Move location'}
                </button>
              </div>
              {movePinMode ? (
                <p className="mb-2 text-xs text-amber-200">
                  Moving this pin changes the location for all stories at this pin ({pinStoryCount}).
                </p>
              ) : (
                <p className="mm-muted mb-2 text-xs">
                  Confirm this is where the memory should appear. Move the pin if needed.
                </p>
              )}
              {locationSummary ? <p className="mm-muted mb-2 text-[11px]">{locationSummary}</p> : null}
              <div className="min-h-56 overflow-hidden rounded-xl">
                <MapCanvas
                  key={`${story.id}-${pin.id}-${movePinMode ? 'move' : 'view'}`}
                  area={area}
                  pins={mapPins}
                  mode={mapMode}
                  embedded
                  highlightedPinId={pin.id}
                  onPinClick={() => {}}
                  placementMode={movePinMode}
                  placementPreview={null}
                  onMapClick={
                    movePinMode
                      ? (p) => {
                          setPlacement((prev) => ({
                            lat: p.lat ?? prev?.lat ?? pin.lat,
                            lng: p.lng ?? prev?.lng ?? pin.lng,
                            x: p.x ?? prev?.x ?? pin.x_position,
                            y: p.y ?? prev?.y ?? pin.y_position,
                          }))
                        }
                      : undefined
                  }
                  locateTarget={locateTarget}
                  initialView={mapView?.geo ?? null}
                  imageFocus={mapView?.image ?? null}
                />
              </div>
            </section>
          ) : null}

          <section className="mb-4 grid gap-3 sm:grid-cols-2">
            <label className="block text-xs">
              <span className="mm-muted">Memory title</span>
              <input
                value={draft.title}
                onChange={(e) => setDraft((d) => ({ ...d, title: e.target.value }))}
                className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              />
            </label>
            <label className="block text-xs">
              <span className="mm-muted">Year</span>
              <input
                type="number"
                value={draft.eventYear}
                onChange={(e) => setDraft((d) => ({ ...d, eventYear: e.target.value }))}
                className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              />
            </label>
            <label className="block text-xs sm:col-span-2">
              <span className="mm-muted">Event date (optional)</span>
              <input
                type="date"
                value={draft.eventDate}
                onChange={(e) => setDraft((d) => ({ ...d, eventDate: e.target.value }))}
                className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              />
            </label>
            <label className="block text-xs sm:col-span-2">
              <span className="mm-muted">Description / note</span>
              <textarea
                value={draft.description}
                onChange={(e) => setDraft((d) => ({ ...d, description: e.target.value }))}
                rows={4}
                className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              />
            </label>
            <label className="block text-xs sm:col-span-2">
              <span className="mm-muted">Tags (comma separated)</span>
              <input
                value={draft.tagsInput}
                onChange={(e) => setDraft((d) => ({ ...d, tagsInput: e.target.value }))}
                className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              />
            </label>
            <label className="block text-xs">
              <span className="mm-muted">Uploaded by</span>
              <input
                value={draft.loggedByDisplayName}
                onChange={(e) => setDraft((d) => ({ ...d, loggedByDisplayName: e.target.value }))}
                className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              />
            </label>
            <label className="block text-xs">
              <span className="mm-muted">Review level</span>
              <select
                value={draft.riskLevel}
                onChange={(e) => setDraft((d) => ({ ...d, riskLevel: e.target.value as RiskLevel }))}
                className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              >
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="admin_review">Admin review</option>
              </select>
            </label>
          </section>

          {pin ? (
            <section className="mb-4 mm-card rounded-xl p-3">
              <p className="text-xs font-bold uppercase tracking-wide text-white/50">Pin details</p>
              <p className="mm-muted mt-1 text-xs">
                {pinStoryCount} stor{pinStoryCount === 1 ? 'y' : 'ies'} at this pin · Pin status: {pin.status}
              </p>
              <div className="mt-3 grid gap-3 sm:grid-cols-2">
                <label className="block text-xs">
                  <span className="mm-muted">Pin name</span>
                  <input
                    value={draft.pinTitle}
                    onChange={(e) => setDraft((d) => ({ ...d, pinTitle: e.target.value }))}
                    className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
                  />
                </label>
                <label className="block text-xs">
                  <span className="mm-muted">Category</span>
                  <select
                    value={draft.pinCategoryId}
                    onChange={(e) => setDraft((d) => ({ ...d, pinCategoryId: e.target.value }))}
                    className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
                  >
                    <option value="">—</option>
                    {categories.filter((c) => c.is_active).map((c) => (
                      <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                  </select>
                </label>
                <label className="block text-xs sm:col-span-2">
                  <span className="mm-muted">Pin description (optional)</span>
                  <input
                    value={draft.pinDescription}
                    onChange={(e) => setDraft((d) => ({ ...d, pinDescription: e.target.value }))}
                    className="mt-1 w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
                  />
                </label>
              </div>
              <p className="mm-muted mt-2 text-xs">
                Stats: {pinStats(pin, stories).approved} approved · {pinStats(pin, stories).pending} pending
              </p>
            </section>
          ) : null}

          <StoryApprovalSummary
            story={{
              ...story,
              risk_level: draft.riskLevel,
              title: draft.title,
              event_year: parseInt(draft.eventYear, 10) || story.event_year,
            }}
            pin={pin ? { ...pin, title: draft.pinTitle } : null}
            area={area}
            category={categories.find((c) => c.id === draft.pinCategoryId) ?? null}
            checks={governanceChecks}
          />
          <div className="mt-3">
            <StoryGovernancePanel
              story={story}
              checks={governanceChecks}
              onChange={setGovernanceChecks}
              approvalNote={approvalNote}
              onApprovalNoteChange={setApprovalNote}
            />
          </div>

          {needsConfirm ? (
            <label className="mt-3 flex items-start gap-2 text-xs">
              <input
                type="checkbox"
                checked={publishConfirmed}
                onChange={(e) => setPublishConfirmed(e.target.checked)}
                className="mt-0.5"
              />
              I have reviewed this story and confirm it may be published.
            </label>
          ) : null}

          {moveStoryOpen ? (
            <div className="mt-4 mm-card space-y-2 rounded-xl p-3">
              <p className="text-sm font-bold">Move story to another pin</p>
              <select
                value={moveAreaId}
                onChange={(e) => setMoveAreaId(e.target.value)}
                className="w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              >
                {areas.map((a) => (
                  <option key={a.id} value={a.id}>{a.name}</option>
                ))}
              </select>
              <div className="max-h-32 space-y-1 overflow-y-auto">
                {pins
                  .filter((p) => p.area_id === moveAreaId && p.id !== pin?.id && !['deleted', 'archived'].includes(p.status))
                  .map((p) => (
                    <button
                      key={p.id}
                      type="button"
                      onClick={() => {
                        setMovePinId(p.id)
                        setMoveNewPinTitle('')
                      }}
                      className={`w-full rounded-lg p-2 text-left text-xs ${movePinId === p.id ? 'mm-bg-accent-20' : 'bg-white/5'}`}
                    >
                      {p.title}
                    </button>
                  ))}
              </div>
              <input
                value={moveNewPinTitle}
                onChange={(e) => {
                  setMoveNewPinTitle(e.target.value)
                  if (e.target.value) setMovePinId(null)
                }}
                placeholder="Or create new pin for this story"
                className="w-full rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-sm"
              />
              <div className="flex gap-2">
                <button type="button" disabled={saving} onClick={() => void onMoveStorySubmit()} className="mm-btn-primary rounded-lg px-3 py-1.5 text-xs font-bold">
                  Move story
                </button>
                <button type="button" onClick={() => setMoveStoryOpen(false)} className="mm-btn-secondary rounded-lg px-3 py-1.5 text-xs font-bold">
                  Cancel
                </button>
              </div>
            </div>
          ) : null}
        </div>

        <div className="shrink-0 border-t border-white/10 px-4 py-3">
          {ownStoryBlocked ? (
            <p className="mb-3 rounded-xl border border-amber-400/40 bg-amber-500/10 px-3 py-2 text-xs text-amber-100">
              {OWN_STORY_APPROVAL_MESSAGE}
            </p>
          ) : platformOverride ? (
            <p className="mm-muted mb-3 text-xs">{PLATFORM_ADMIN_OVERRIDE_NOTE}</p>
          ) : null}
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy || saving || ownStoryBlocked}
              title={ownStoryBlocked ? OWN_STORY_APPROVAL_MESSAGE : undefined}
              onClick={() => void onApproveClick()}
              className="mm-btn-primary rounded-lg px-3 py-2 text-xs font-bold disabled:cursor-not-allowed disabled:opacity-40"
            >
              Approve
            </button>
            <button type="button" disabled={busy || saving} onClick={() => void onSave()} className="mm-btn-secondary rounded-lg px-3 py-2 text-xs font-bold disabled:opacity-50">
              Save changes
            </button>
            <button type="button" onClick={() => setMoveStoryOpen(true)} className="mm-btn-secondary rounded-lg px-3 py-2 text-xs font-bold">
              Move story
            </button>
            <button type="button" onClick={onReject} className="rounded-lg border border-red-400/40 px-3 py-2 text-xs font-bold text-red-300">
              Reject
            </button>
            <button type="button" onClick={onClose} className="mm-btn-secondary rounded-lg px-3 py-2 text-xs font-bold">
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
