-- Tunable consistency model: one row per season (app merges with code defaults when missing)
create table if not exists public.consistency_model_settings (
  id bigint generated by default as identity primary key,
  season integer not null unique,
  error_divisor double precision not null default 30,
  min_trust_floor double precision not null default 0.20,
  trusted_anchor_min_matches integer not null default 4,
  trusted_anchor_min_adjusted_consistency double precision not null default 0.60,
  usable_reference_min_matches integer not null default 3,
  usable_reference_min_adjusted_consistency double precision not null default 0.45,
  unstable_min_matches integer not null default 2,
  strong_opponent_step double precision not null default 0.15,
  max_strong_opponent_count integer not null default 2,
  updated_at timestamptz not null default now()
);

create index if not exists consistency_model_settings_season_idx
  on public.consistency_model_settings (season);
